### ISSUE TITLE
(StarDict) dictionaries can't be recognized.

### ISSUE THREAD

**Issue by Achaean** [a-rodin/qstardict#10]
Hi! :-)
I'm on Debian Jessie x64 KDE and I tried both the version from repositories and this version from here (which I compiled).

QStarDict runs properly, but can't "see" the dictionaries.

I tried both the common directory (for all users,  /usr/share/stardict/dic/ ) and my personal directory (~/.stardict/dic/).

**Comment by Ri0n** [comment]
Broken/incompatible dictionaries?

**Comment by Achaean** [comment]
Well...I'm using them for years.
I just copied them from another system.

**Comment by Ri0n** [comment]
did you try /usr/share/qstardict/dic/ ? This directory works perfect for me.
Btw the latest (git) version of qstartdict may be a little confusing from plugins settings ui point of view. I'm working on it now. But I hope stardict plugin is enabled and works properly.

**Comment by Achaean** [comment]
Indeed!
I redownloaded some dicts from http://download.huzheng.org/ and they are properly working.
Seems like it was only, a copy error.
My fault! :-)
Thanks!!!
