### ISSUE TITLE
Issue with installing on Ubuntu 16.04

### ISSUE THREAD

**Issue by edr0id** [a-rodin/qstardict#12]
Hi, I'm having a problem installing qstardict 1.2rc1 or fresh git from sources.

OS: Ubuntu 16.04 based
QT: 5.7

qmake runs fine on both branches:

>Project MESSAGE: Enabled plugins: stardict web                                                                           
Project MESSAGE: D-Bus support: enabled                                                                                  
Project MESSAGE: Translations: enabled                                                                                   
Project MESSAGE: Install prefix: /usr                                                                                    
Project MESSAGE: Binary directory: /usr/bin                                                                              
Project MESSAGE: Data directory: /usr/share/qstardict                                                                    
Project MESSAGE: Translations directory: /usr/share/qstardict/translations                                               
Project MESSAGE: Plugins directory: /usr/lib/qstardict/plugins                                                           
Project MESSAGE: Documentation directory: /usr/share/doc/qstardict

**make with 1.2rc1**:
>application.cpp:30:31: fatal error: qxtglobalshortcut.h: No such file or directory
compilation terminated.
Makefile:724: recipe for target 'application.o' failed
make[1]: *** [application.o] Error 1
make[1]: Leaving directory '/home/ed/Downloads/qstardict-1.2rc1/qstardict'
Makefile:43: recipe for target 'sub-qstardict-make_first' failed
make: *** [sub-qstardict-make_first] Error 2

**make with today's (20170215) git**:
>../qxt/qxtglobalshortcut_x11.cpp:37:45: fatal error: qpa/qplatformnativeinterface.h: No such file or directory
 #include <qpa/qplatformnativeinterface.h>
                                             ^
compilation terminated.
Makefile:923: recipe for target 'qxtglobalshortcut_x11.o' failed
make[1]: *** [qxtglobalshortcut_x11.o] Error 1
make[1]: Leaving directory '/home/ed/Downloads/qstardict-master/qstardict'
Makefile:43: recipe for target 'sub-qstardict-make_first' failed
make: *** [sub-qstardict-make_first] Error 2

Let me know if I can provide some more details.

**Comment by Ri0n** [comment]
Not sure about Ubuntu, but on Gentoo system the header is installed with qtgui package and located at /usr/include/qt5/QtGui/5.7.1/QtGui/qpa/qplatformnativeinterface.h

**Comment by a-rodin** [comment]
In Ubuntu this header could be installed with package `qtbase5-private-dev`.

**Comment by edr0id** [comment]
Yes, that's the right package, everything compiles correctly now, thank you guys !
