### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by GreatBigWhiteWorld** [a-rodin/qstardict#13]
I am trying to install/compile qstardict for my openSUSE. Following the instruction:

Before building fetch libqxt submodule:

git submodule init && git submodule update
To build and install:

qmake [switches]
make
make install

But when I do git submodule init, the error comes:

fatal: Not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

**Comment by Totktonada** [comment]
Submodules were removed since last release candidate: https://github.com/a-rodin/qstardict/compare/1.2rc1...master . If it causes problems, I guess, it worth to request drop new release / rc without submodules. As an workaround I would be suggest you try to build current master.

**Comment by GreatBigWhiteWorld** [comment]
Thanks for the answer. Trying to build the master build, the errors are:

kdeintegration.cpp:22:31: fatal error: KStatusNotifierItem: No such file or directory
 #include <KStatusNotifierItem>
                               ^
compilation terminated.
make[2]: *** [Makefile:272: kdeintegration.o] Error 1
make[2]: Leaving directory '/./qstardict-master/plugins/kdeintegration'
make[1]: *** [Makefile:85: sub-kdeintegration-make_default] Error 2
make[1]: Leaving directory '/./qstardict-master/plugins'
make: *** [Makefile:62: sub-plugins-make_default] Error 2

The system is openSUSE Tumbleweed plasma5 update to date.

**Comment by Totktonada** [comment]
Missed kwindowsystem package?

I can leave full dependencies list from the corresponding Gentoo ebuild as the reference:

```
DEPEND="
    dev-libs/glib:2
    qt4? (
        dev-qt/qtgui:4
        dbus? ( dev-qt/qtdbus:4 )
        plugin_swac? ( dev-qt/qtsql:4 )
    )
    qt5? (
        dev-qt/qtgui:5
        dev-qt/qtnetwork:5
        dev-qt/qtprintsupport:5
        dev-qt/qtwidgets:5
        dev-qt/qtxml:5
        dev-qt/linguist-tools:5
        dbus? ( dev-qt/qtdbus:5 )
        plugin_swac? ( dev-qt/qtsql:5 )
    )
    kde? (
        kde-frameworks/kwindowsystem
    )
```

**Comment by GreatBigWhiteWorld** [comment]
It seems I did lack the kwindowsystem-dev package. I installed them as well as the .dev-32bit version.

But the error is still the same.

Then I installed the qt4,qt5 dev patterns with suse Yast, about a few hundred MBs of packages 

The error is still the same.

**Comment by a-rodin** [comment]
Indeed, it seems like you are trying to build 1.2rc1 that used git submodules. I created a new [1.2 release](https://github.com/a-rodin/qstardict/releases/tag/1.2). Please try to build it instead.

**Comment by GreatBigWhiteWorld** [comment]
@a-rodin Is it the same with the master build @Totktonada suggested? Because I have tried to build it but can't fix the "kdeintegration.cpp:22:31: fatal error: KStatusNotifierItem: No such file or directory" error.

BTW, I don't know coding. Just want to install qstardict following your compile instructions.

**Comment by a-rodin** [comment]
@GreatBigWhiteWorld It is because the QStarDict detects that you have KDE and tries to build KDE plugin. If you don't really need this KDE integration plugin, you can disable it by doing
```bash
qmake ENABLED_PLUGINS="stardict web"
```
instead of plain
```bash
qmake
```

**Comment by GreatBigWhiteWorld** [comment]
@a-rodin I tried make clean, then
`qmake ENABLED_PLUGINS="stardict web"
`
then "make", and it's the same error in the end

kdeintegration.cpp:22:31: fatal error: KStatusNotifierItem: No such file or directory

**Comment by a-rodin** [comment]
@GreatBigWhiteWorld I disabled this kde integration plugin from being built by default. Please try do do `git clone https://github.com/a-rodin/qstardict/ && qmake && make`.

@Ri0n Could you please take a look at this issue with the KDE integration plugin?

**Comment by Ri0n** [comment]
Well I found multiple problems.
`qmake ENABLED_PLUGINS="stardict web"` does not properly updates Makefiles.
It's required to start `qmake ENABLED_PLUGINS="stardict web" -recursive` instead.

Then `make clean` does not delete *.so files and maybe some other.

Also probably more precise checks are needed to detect whether kde plugin should be built or not.

But generally there is nothing wrong with plugins.pri.

I'd suggest to do `git clean -xfd .` before each next compilation attempt.

**Comment by Ri0n** [comment]
Well actually `make distclean` does the trick with removing all the binaries.

**Comment by Ri0n** [comment]
I can't find info on how to force qmake update makefiles w/o additional arguments. Probably it's impossible. 

I think this bug should be closed. Nothing more to discuss here.

**Comment by Ri0n** [comment]
@GreatBigWhiteWorld, I think you build with Qt4. try to switch to Qt5.

**Comment by a-rodin** [comment]
@Ri0n Let's wait for response of the issue reporter and close it when @GreatBigWhiteWorld report successful build.

**Comment by GreatBigWhiteWorld** [comment]
Thank you all! It's finally working.
What I did was:

```
make distclean
qmake ENABLED_PLUGINS="stardict web" -recursive
sudo make install
```

It's completed successfully and running. I don't know if it's because of "distclean" or "-recursive". Maybe update the compile instruction a bit?
