### ISSUE TITLE
sametypesequence=h does not work

### ISSUE THREAD

**Issue by marmistrz** [a-rodin/qstardict#15]
The `.ifo` file:

```
StarDict's dict ifo file
version=2.4.2
bookname=name
wordcount=XXXX
idxfilesize=YYYY
sametypesequence=h
```
 
Displayed by QStarDict 1.1 as:
_color="#0000E0">coni._

Displayed by Stardict 3.0.6 as: (correctly) (GitHub doesn't show the blue color)
I <span style="color:blue">_coni._</span>

Referenced by the Stardict format reference as _html codes_: http://stardict-4.sourceforge.net/StarDictFileFormat
See also the notes is the relevant issue for the (no longer developed) QStarDict QML interface for SailfishOS: https://github.com/d0b3rm4n/harbour-sidudict/issues/1

I'm probably not permitted to publicly share the dictionary. If you'd like me to send it to you for development purposes, please contact me via e-mail.

**Comment by a-rodin** [comment]
Fixed in #24
