### ISSUE TITLE
Consider porting away from libqxt

### ISSUE THREAD

**Issue by hosiet** [a-rodin/qstardict#16]
Dear qstardict developers,

Now that libqxt project is [abandoned since 2014](https://bitbucket.org/libqxt/libqxt/wiki/Home), please consider porting away from libqxt code to ease its maintenance in the future.

**Comment by Totktonada** [comment]
@hosiet Thanks for giving our attention to that! We use relatively small amount of libqxt code for global hotkeys support. So we can consider such porting away as already done.

I guess the issue can be closed.
