### ISSUE TITLE
Disgusting config path

### ISSUE THREAD

**Issue by lahwaacz** [a-rodin/qstardict#23]
The config path changed from `~/.config/qstardict/qstardict.conf` to `~/.config/Unknown Organization/qstardict.conf` in version 1.3.

**Comment by a-rodin** [comment]
It seems like it was changed in fa42fc3c. @Ri0n Does https://github.com/a-rodin/qstardict/blob/master/qstardict/application.cpp#L48 still break XDG dir structure, or we can put `setOrganizationName` back?

**Comment by Ri0n** [comment]
The idea was to remove organization name at all from the path. Keep just product name.
For now I don't know. I'll check
