### ISSUE TITLE
Questions.

### ISSUE THREAD

**Issue by Achaean** [a-rodin/qstardict#25]
Hi! :-)

1) Probably a silly question, but where D-Bus is needed?
I compiled QStarDict without d-bus and I can't see any visible difference.
With what applications needs qstardict to communicate?

2) How a translation can be made (and added to already existing)?
Where are the to-be translated texts?

**TIA!** :-)
A.

**Comment by a-rodin** [comment]
Take a look at the wiki articles https://github.com/a-rodin/qstardict/wiki/Hiding-and-showing-QStarDict-window-with-DBus and https://github.com/a-rodin/qstardict/wiki/How-to-make-a-translation .
