### ISSUE TITLE
StarDict 0.12.9 doesn't detect a dictionary

### ISSUE THREAD

**Issue by marmistrz** [a-rodin/qstardict#5]
I have a dictionary which opens properly in Stardict 3.0.5. It requires the HTML data parsing plugin, though. QStarDict 0.12.9 doesn't detect it at all.

**Comment by marmistrz** [comment]
And how can these modern dictionaries be converted so as to be supported by SD 2.x and QSD?

**Comment by a-rodin** [comment]
I think that the best way to support then is to use special plugin for them that uses dictionary parser from ColorDict.

**Comment by marmistrz** [comment]
The solution was to edit the .ifo file and set the version to 2.4.2
