### ISSUE TITLE
'Win' modifierKey does not work on a PC/Win keyboard connected to macbook (OS X)

### ISSUE THREAD

**Issue by ildar-aim** [a-rodin/qstardict#7]
Could you add 
-Scroll Lock
-Menu
-something else 
modifier keys to the 
SettingsDialog::SettingsDialog function
https://github.com/a-rodin/qstardict/blob/master/qstardict/settingsdialog.cpp
?

My enviroment 
Host OS  - OS X El Capitan
Guest OS - arch linux XFCE4 under virtualbox
PC/Win keyboard like this 
http://www.minus40.info/ice/pics/pckeyboard.gif

**Comment by a-rodin** [comment]
It seems a bit difficult to add modifiers that are not from Qt::KeyboardModifier enum (http://doc.qt.io/qt-4.8/qt.html#KeyboardModifier-enum)
Btw did you try to press Ctrl when actually "Win" modifier is selected? Qt documentation says, that "Meta key" (which is named in QStarDict as "Win") corresponds to Control on Mac.

**Comment by ildar-aim** [comment]
I have used this version 
https://www.archlinux.org/packages/community/i686/qstardict/

There is no "Show translation popup by shortcut" option. 
![_2015-12-21_09-49-51](https://cloud.githubusercontent.com/assets/1235868/11925032/3a676a60-a7c8-11e5-9fa3-8a84e2fda8a8.png)


Should I flag the Package as Out-of-Date on the page
https://www.archlinux.org/packages/community/i686/qstardict/ ?
Please confirm.

The history of the package 
https://projects.archlinux.org/svntogit/community.git/log/trunk?h=packages/qstardict

---------

**Comment by a-rodin** [comment]
Yes, this feature existed only in git version. 
I've released version 1.1 which has this option just now, so you can mark the package as an obsolete.

**Comment by ildar-aim** [comment]
The package has been flagged.

I suppose you can close the ticket.

Thank you for your help.
