### ISSUE TITLE
qstardict 1.1: if indicator-plugin is used, there is no way to show main window

### ISSUE THREAD

**Issue by selivan** [a-rodin/qstardict#8]
qstardict: 1.1
qt: 4.8.6

On Ubuntu 14.04 with XFCE, if indicator-plugin is used, qstardict tray icon is displayed as indicator. Indicators do not have separate left- and right-click action, it shows menu on left-click and indicator plugin menu(configure, remove, ...) on right-click. I suppose, indicator plugin in Unity/Gnome3 have similar behavior.

So it would be nice to add "Show main window" item to tray menu.

**Comment by a-rodin** [comment]
I consider adding this feature to the future release of QStarDict

**Comment by a-rodin** [comment]
Added it to the master branch.
